### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by germant13** [kblin/ncbi-acc-download#15]
Hi! 
I am writing because I have a problem to run the script
I installed by pip according the instructions but when I tried to run I received this message

german@lbc4:~/GWASproject/GMT_GWAS$ ncbi-acc-download -v --recursive QDXZ00000000.1
Traceback (most recent call last):
  File "/usr/local/bin/ncbi-acc-download", line 7, in <module>
    from ncbi_acc_download.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/ncbi_acc_download/__main__.py", line 65
    print(err, file=sys.stderr)
^
SyntaxError: invalid syntax

Also, I tried with the command:  ncbi-acc-download --help
And I received the same message.

Do you know what is the problem?

Best

German

**Comment by kblin** [comment]
Interesting. What commands did  you use to install `ncbi-acc-download`?

**Comment by germant13** [comment]
I used: 
sudo pip install ncbi-acc-download

also I tried to upgrade pip, but nothing...

**Comment by debaleena-bhowmik** [comment]
I used 
conda install -c bioconda ncbi-acc-download
for installation

And tried to run the given example 
ncbi-acc-download -m protein WP_015663423.1
But got the same error.

**Comment by kblin** [comment]
Ok, I finally had some time to follow up on that, and the issue is that Python 2.7 doesn't like the print function without further help. I apparently didn't test that change on Python 2.7, sorry about that.

As Python 2.7 reached its end of life on January 1st and I'm not planning to further work on Python 2.7 compatibility, you have 2 options:
* install ncbi-acc-download 0.2.6 in a Python3 envrionment
* use ncbi-acc-download 0.2.5

For the former, you need to use 
`pip uninstall ncbi-acc-download && pip3 install ncbi-acc-download` if you installed using pip. I recommend using virtual environments for this, but system-wide will work.

For conda, use `conda create -c bioconda -n mypython3 python=3 ncbi-acc-download`

If you want to keep a Python 2 based install, use

`pip install --upgrade ncbi-acc-download==0.2.5` if you've used pip and `conda install -c bioconda ncbi-acc-download==0.2.5` if you've used conda.
