### ISSUE TITLE
Download a GFF file [feature request]

### ISSUE THREAD

**Issue by sjackman** [kblin/ncbi-acc-download#4]
Is it possible to download a GFF file?

**Comment by sjackman** [comment]
Look what I just found!
https://www.biostars.org/p/296825/
https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?db=nuccore&report=gff3&id=NC_005278.1
I'm suddenly very happy!

**Comment by sjackman** [comment]
Other useful types…
fasta FASTA
fasta_cds_aa FASTA of CDS Products
fasta_cds_na FASTA of Coding Regions
ft Feature Table
gb GenBank Flatfile
See https://www.ncbi.nlm.nih.gov/books/NBK179288/

Could you please add `ft` (Feature table) and `gff3`?

**Comment by kblin** [comment]
I was going off the formats documented in https://www.ncbi.nlm.nih.gov/books/NBK25499/table/chapter4.T._valid_values_of__retmode_and/?report=objectonly :smile:

`ft` is easy to add.

`gff3` I'm a bit weary about because that changes URL, parameters and a lot of other internals, as well as not being an officially supported API.

**Comment by sjackman** [comment]
`gff3` is so useful! It's the only format that IGV can read. Hopefully NCBI add it to their standard API.
Thanks for adding `ft`.

**Comment by kblin** [comment]
Support for both formats has been added in version 0.2.0

**Comment by sjackman** [comment]
Thanks, Kai!
